### ISSUE TITLE
Action sheet menu is not aligned in center when orientation changes on ipad

### ISSUE THREAD

**Issue by skharpreet** [EddyVerbruggen/cordova-plugin-actionsheet#16]
The action sheet menu is not aligned in center in iPad 3 when we change the orientation from portrait to landscape or vice versa.
Attached are the screen shots for reference.

![img_0431](https://cloud.githubusercontent.com/assets/5449508/6457668/3217894a-c19f-11e4-9b1a-6d2f84167cb3.PNG)
![img_0433](https://cloud.githubusercontent.com/assets/5449508/6457667/3215f7b0-c19f-11e4-975e-37b526ca97a5.PNG)

**Comment by Vinoth18** [comment]
+1
Or it is good if we have the hide method, so internally we can call the hide method on orientation change.

**Comment by EddyVerbruggen** [comment]
Just to be sure: this happens only when rotating the device while the actionsheet is being displayed, right?

**Comment by skharpreet** [comment]
Yeah. thats true, it happens when the orientation is changed while the action sheet is displayed.

Firstly this should be fixed but as a workaround I was thinking to close the menu when the orientation changes, but there is no close/hide method in the plugin. I am a kind of stuck at this point.

**Comment by EddyVerbruggen** [comment]
Hi, @skharpreet and @Vinoth18 please test the 1.1.4 release of this plugin, it has a working `hide()` function for iOS.

**Comment by Vinoth18** [comment]
Thanks @EddyVerbruggen , hide is working.

**Comment by napolitano** [comment]
Hi, i would celebrate a working fix for the still existing issue. Currently it is possible to hide the sheet on orientation change or resize, but because it seem to work properly on android you must make a decision: Have different behavior or degrade user experience for android.

Are there any news related to this bug? Is a fix still work in progress or is it currently unfixable?

**Comment by EddyVerbruggen** [comment]
Hi @napolitano why would you degrade experience on Android if you can hide it for iOS only?

And I'm not working on a fix currently (perhaps someone else is?) as I don't have to for it atm...

**Comment by napolitano** [comment]
Hi @EddyVerbruggen. Thank you for the surprisingly quick response.  It's simply, because i prefer consistent behavior across platforms if possible ;) In this case we'll do what's suggested: Hide it on resize/orientation change only for iOS. 

I can really live with the hide()-workaround, but it would be great if there will be a fix. Will see if i can do something. If yes, i will send a pull request to let you decide whether to use it or not.

**Comment by EddyVerbruggen** [comment]
That would be awesome @napolitano, in any case: good luck with your app!
